import Foundation

// MARK: - Pano gecmisi

/// Kopyalanan bir sey: metin ya da gorsel (PNG verisi).
public struct ClipboardEntry: Sendable, Equatable, Identifiable {
    public let id: UUID
    public let text: String?
    public let image: Data?
    public var pinned: Bool
    public let copiedAt: Date

    public init(text: String? = nil, image: Data? = nil, pinned: Bool = false, copiedAt: Date = Date()) {
        self.id = UUID()
        self.text = text
        self.image = image
        self.pinned = pinned
        self.copiedAt = copiedAt
    }
}

/// Son kopyalananlar, yalniz bellekte. Windows karsiligi: Services/ClipboardHistoryService.cs.
/// En fazla 25; sabitlenenler basta durur ve hic dusmez; ayni metin tekrar kopyalaninca one gelir.
public struct ClipboardHistory: Sendable {
    public static let capacity = 25
    public private(set) var entries: [ClipboardEntry] = []

    public init() {}

    /// Parola yoneticilerinin isaretledigi (gizli ya da gecici) veriler hic kaydedilmez
    /// (nspasteboard.org sozlesmesi; 1Password, Bitwarden, KeePassXC kullanir).
    public static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "com.typeit4me.clipping", "de.petermaurer.TransientPasteboardType",
    ]

    public static func shouldRecord(types: [String]) -> Bool {
        !types.contains { ignoredTypes.contains($0) }
    }

    public mutating func add(_ entry: ClipboardEntry) {
        if let text = entry.text {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return }
            if let i = entries.firstIndex(where: { $0.text == text }) {
                // Ayni metin: one alinir, sabitlemesi korunur.
                let pinned = entries[i].pinned
                entries.remove(at: i)
                insert(ClipboardEntry(text: text, pinned: pinned))
                return
            }
        } else if entry.image == nil {
            return
        } else if let data = entry.image, entries.first(where: { !$0.pinned })?.image == data {
            return
        }
        insert(entry)
    }

    private mutating func insert(_ entry: ClipboardEntry) {
        let firstUnpinned = entries.firstIndex { !$0.pinned } ?? entries.count
        entries.insert(entry, at: entry.pinned ? 0 : firstUnpinned)
        // Kapasite asilirsa en eski sabitlenmemis dusurulur.
        while entries.count > Self.capacity, let last = entries.lastIndex(where: { !$0.pinned }) {
            entries.remove(at: last)
        }
    }

    public mutating func togglePin(_ id: UUID) {
        guard let i = entries.firstIndex(where: { $0.id == id }) else { return }
        var entry = entries.remove(at: i)
        entry.pinned.toggle()
        let firstUnpinned = entries.firstIndex { !$0.pinned } ?? entries.count
        entries.insert(entry, at: entry.pinned ? 0 : firstUnpinned)
    }

    public mutating func remove(_ id: UUID) { entries.removeAll { $0.id == id } }

    /// Sabitlenenler kalir.
    public mutating func clear() { entries.removeAll { !$0.pinned } }
}

// MARK: - Hisseler (Stooq)

/// Windows karsiligi: Services/StockService.cs -> StockQuote.
public struct StockQuote: Sendable, Equatable {
    public let symbol: String
    public let close: Double
    public let previousClose: Double?
    public let history: [Double]
    public let date: Date

    public var changePercent: Double? {
        guard let previousClose, previousClose != 0 else { return nil }
        return (close - previousClose) / previousClose * 100
    }
}

public enum StockData {
    /// "AAPL, MSFT; ^spx" -> sirali ve tekrarsiz semboller.
    public static func splitSymbols(_ text: String) -> [String] {
        var seen = Set<String>()
        return text.split(whereSeparator: { $0 == "," || $0 == ";" || $0 == " " })
            .map { $0.trimmingCharacters(in: .whitespaces).uppercased() }
            .filter { stooqSymbol($0) != nil && seen.insert($0).inserted }
    }

    /// Stooq'taki adi ("AAPL" -> "aapl.us"); sembol olmayan metin icin nil.
    public static func stooqSymbol(_ symbol: String) -> String? {
        let s = symbol.trimmingCharacters(in: .whitespaces).lowercased()
        guard (1...20).contains(s.count),
              s.allSatisfy({ ($0.isASCII && ($0.isLetter || $0.isNumber)) || ".^-_".contains($0) }) else { return nil }
        return s.hasPrefix("^") || s.contains(".") ? s : s + ".us"
    }

    public static func url(for symbol: String, today: Date = Date()) -> URL? {
        guard let stooq = stooqSymbol(symbol) else { return nil }
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "yyyyMMdd"
        let start = today.addingTimeInterval(-30 * 86_400)
        var c = URLComponents(string: "https://stooq.com/q/d/l/")!
        c.queryItems = [URLQueryItem(name: "s", value: stooq), URLQueryItem(name: "i", value: "d"),
                        URLQueryItem(name: "d1", value: f.string(from: start)), URLQueryItem(name: "d2", value: f.string(from: today))]
        return c.url
    }

    /// Stooq gunluk CSV'si ("Date,Open,High,Low,Close,Volume"); "No data" ya da fiyatsiz cevap icin nil.
    public static func parse(_ symbol: String, csv: String) -> StockQuote? {
        let lines = csv.split(whereSeparator: \.isNewline).map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty }
        guard lines.count >= 2 else { return nil }
        let header = lines[0].split(separator: ",").map { $0.lowercased() }
        guard let dateColumn = header.firstIndex(of: "date"), let closeColumn = header.firstIndex(of: "close") else { return nil }
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.timeZone = TimeZone(identifier: "UTC")
        f.dateFormat = "yyyy-MM-dd"
        var days: [(Date, Double)] = []
        for line in lines.dropFirst() {
            let fields = line.split(separator: ",", omittingEmptySubsequences: false).map(String.init)
            guard fields.count > max(dateColumn, closeColumn), let date = f.date(from: fields[dateColumn]),
                  let close = Double(fields[closeColumn]), close > 0 else { continue }
            days.append((date, close))
        }
        guard !days.isEmpty else { return nil }
        days.sort { $0.0 < $1.0 }
        let latest = days[days.count - 1]
        return StockQuote(symbol: symbol.uppercased(), close: latest.1, previousClose: days.count > 1 ? days[days.count - 2].1 : nil,
                          history: days.map(\.1), date: latest.0)
    }
}

// MARK: - Doviz ve kripto

/// Windows karsiligi: Services/CurrencyService.cs -> CurrencyQuote.
public struct CurrencyQuote: Sendable, Equatable {
    public let base: String
    public let target: String
    public let rate: Double
    public let previous: Double?
    public let history: [Double]
    public let isCrypto: Bool

    public var changePercent: Double? {
        guard let previous, previous != 0 else { return nil }
        return (rate - previous) / previous * 100
    }

    /// Kullanicinin yazdigi: para birimi ya da coin.
    public var symbol: String { isCrypto ? base : target }
}

public enum CurrencyData {
    /// Avrupa Merkez Bankasi'nin yayimladiklari (Frankfurter).
    public static let supported: Set<String> = [
        "AUD", "BGN", "BRL", "CAD", "CHF", "CNY", "CZK", "DKK", "EUR", "GBP", "HKD", "HUF", "IDR", "ILS", "INR", "ISK",
        "JPY", "KRW", "MXN", "MYR", "NOK", "NZD", "PHP", "PLN", "RON", "SEK", "SGD", "THB", "TRY", "USD", "ZAR",
    ]

    /// Coin sembolleri ve CoinGecko kimlikleri (Windows'la ayni liste).
    public static let cryptoIds: [String: String] = [
        "BTC": "bitcoin", "ETH": "ethereum", "SOL": "solana", "BNB": "binancecoin", "XRP": "ripple",
        "ADA": "cardano", "DOGE": "dogecoin", "TRX": "tron", "TON": "the-open-network", "DOT": "polkadot",
        "AVAX": "avalanche-2", "LTC": "litecoin", "LINK": "chainlink", "BCH": "bitcoin-cash", "XLM": "stellar",
        "ATOM": "cosmos", "SHIB": "shiba-inu", "USDT": "tether", "USDC": "usd-coin",
    ]

    /// Ayardaki "TRY, EUR; BTC" -> sirali, tekrarsiz, taban haric.
    public static func targets(_ text: String, base: String) -> [String] {
        var seen = Set<String>()
        return text.split(whereSeparator: { $0 == "," || $0 == ";" || $0 == " " })
            .map { $0.trimmingCharacters(in: .whitespaces).uppercased() }
            .filter { !$0.isEmpty && $0 != base.uppercased() && seen.insert($0).inserted }
    }

    public static func frankfurterURL(base: String, targets: [String], today: Date = Date()) -> URL? {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "yyyy-MM-dd"
        let start = today.addingTimeInterval(-14 * 86_400)
        return URL(string: "https://api.frankfurter.dev/v1/\(f.string(from: start))..\(f.string(from: today))?from=\(base)&to=\(targets.joined(separator: ","))")
    }

    /// Frankfurter aralik cevabi: {"rates": {"2026-09-29": {"TRY": 41.5}, ...}}; her gecmis eskiden yeniye.
    public static func fiatQuotes(base: String, targets: [String], json: Data) -> [CurrencyQuote] {
        guard let root = try? JSONSerialization.jsonObject(with: json) as? [String: Any],
              let rates = root["rates"] as? [String: [String: Double]] else { return [] }
        let days = rates.keys.sorted()
        return targets.compactMap { target in
            let series = days.compactMap { rates[$0]?[target] }
            guard let latest = series.last else { return nil }
            return CurrencyQuote(base: base, target: target, rate: latest,
                                 previous: series.count > 1 ? series[series.count - 2] : nil,
                                 history: series, isCrypto: false)
        }
    }

    public static func coinGeckoURL(coin: String, currency: String) -> URL? {
        guard let id = cryptoIds[coin.uppercased()] else { return nil }
        return URL(string: "https://api.coingecko.com/api/v3/coins/\(id)/market_chart?vs_currency=\(currency.lowercased())&days=14")
    }

    /// CoinGecko fiyat gecmisi ({"prices": [[ms, fiyat], ...]}): son fiyat, 24 saat onceki ve gunluk son fiyatlar.
    public static func cryptoQuote(coin: String, currency: String, json: Data, calendar: Calendar = .current) -> CurrencyQuote? {
        guard let root = try? JSONSerialization.jsonObject(with: json) as? [String: Any],
              let prices = root["prices"] as? [[Any]] else { return nil }
        let points: [(Date, Double)] = prices.compactMap { pair in
            guard pair.count >= 2, let ms = (pair[0] as? NSNumber)?.doubleValue, let price = (pair[1] as? NSNumber)?.doubleValue
            else { return nil }
            return (Date(timeIntervalSince1970: ms / 1000), price)
        }.sorted { $0.0 < $1.0 }
        guard let latest = points.last else { return nil }
        let dayBefore = latest.0.addingTimeInterval(-86_400)
        let previous = points.last { $0.0 <= dayBefore }?.1
        var daily: [Double] = []
        var lastDay: Date?
        for point in points {
            let day = calendar.startOfDay(for: point.0)
            if day == lastDay { daily[daily.count - 1] = point.1 } else { daily.append(point.1); lastDay = day }
        }
        return CurrencyQuote(base: coin.uppercased(), target: currency.uppercased(), rate: latest.1,
                             previous: previous, history: daily, isCrypto: true)
    }
}

// MARK: - Ping

/// Son cevaplar: milisaniye ya da kayip paket (nil). Windows karsiligi: Services/PingService.cs -> PingStats.
public struct PingStats: Sendable {
    public static let window = 30
    public private(set) var samples: [Double?] = []

    public init() {}

    public mutating func add(_ milliseconds: Double?) {
        samples.append(milliseconds)
        if samples.count > Self.window { samples.removeFirst(samples.count - Self.window) }
    }

    private var replies: [Double] { samples.compactMap { $0 } }
    public var latest: Double? { samples.last ?? nil }
    public var lastLost: Bool { !samples.isEmpty && samples.last! == nil }
    public var average: Double? { replies.isEmpty ? nil : replies.reduce(0, +) / Double(replies.count) }
    public var min: Double? { replies.min() }
    public var max: Double? { replies.max() }
    /// Kayip paketler, orneklerin yuzdesi.
    public var loss: Double { samples.isEmpty ? 0 : Double(samples.filter { $0 == nil }.count) * 100 / Double(samples.count) }
    /// Cizgi icin: kayip paket en yavas cevap gibi.
    public var history: [Double] { samples.map { $0 ?? (max ?? 0) } }

    /// 60 ms alti iyi, 150 ms alti orta, ustu kotu (Windows: BrushFor).
    public enum Quality: Sendable { case good, fair, poor }
    public static func quality(_ milliseconds: Double?) -> Quality {
        guard let ms = milliseconds else { return .poor }
        return ms < 60 ? .good : (ms < 150 ? .fair : .poor)
    }

    /// `/sbin/ping -c 1` ciktisindan sure: "... time=12.345 ms"; kayipta nil.
    public static func parse(_ output: String) -> Double? {
        guard let range = output.range(of: "time=") else { return nil }
        let rest = output[range.upperBound...]
        let number = rest.prefix { $0.isNumber || $0 == "." }
        return Double(number)
    }

    /// Hedef: bos ya da gecersizse 1.1.1.1. Komut satirina gecmeden once yalniz ad/adres karakterleri.
    public static let defaultTarget = "1.1.1.1"
    public static func target(_ setting: String?) -> String {
        let t = setting?.trimmingCharacters(in: .whitespaces) ?? ""
        guard !t.isEmpty, t.count <= 253, !t.hasPrefix("-"),
              t.allSatisfy({ ($0.isASCII && ($0.isLetter || $0.isNumber)) || ".-:".contains($0) }) else { return defaultTarget }
        return t
    }
}

// MARK: - Yapilacaklar

public struct TodoTask: Sendable, Equatable, Identifiable {
    public let id: String
    public let text: String
    public let due: Date?

    public init(id: String, text: String, due: Date?) {
        self.id = id
        self.text = text
        self.due = due
    }
}

/// Yerel liste dosyasi, Windows'taki LocalData ile ayni bicim: {"items": [{"id", "text", "createdAt"}]}.
public struct LocalTodoList: Codable, Sendable {
    public struct Item: Codable, Sendable, Equatable {
        public var id: String
        public var text: String
        public var createdAt: String

        public init(text: String, now: Date = Date()) {
            self.id = UUID().uuidString.replacingOccurrences(of: "-", with: "").lowercased()
            self.text = text
            self.createdAt = ISO8601DateFormatter().string(from: now)
        }
    }

    public var items: [Item] = []

    public init() {}

    public init(from decoder: Decoder) throws {
        var r = try JSONObjectReader(decoder)
        items = r("items", [])
    }
}

extension LocalTodoList.Item {
    public init(from decoder: Decoder) throws {
        var r = try JSONObjectReader(decoder)
        id = r("id", UUID().uuidString.lowercased())
        text = r("text", "")
        createdAt = r("createdAt", "")
    }
}

/// Todoist API v1 (Windows karsiligi: Services/TodoistClient.cs).
public enum TodoistData {
    public static let baseURL = "https://api.todoist.com/api/v1/"

    /// {"results": [{"id","content","checked","due":{"date","datetime"}}], "next_cursor": ...}
    public static func page(_ json: Data) -> (tasks: [TodoTask], cursor: String?) {
        guard let root = try? JSONSerialization.jsonObject(with: json) as? [String: Any] else { return ([], nil) }
        let results = root["results"] as? [[String: Any]] ?? []
        let tasks: [TodoTask] = results.compactMap { t in
            guard (t["checked"] as? Bool) != true else { return nil }
            let id = (t["id"] as? String) ?? (t["id"] as? NSNumber)?.stringValue ?? ""
            let due = t["due"] as? [String: Any]
            return TodoTask(id: id, text: t["content"] as? String ?? "",
                            due: parseDue((due?["datetime"] as? String) ?? (due?["date"] as? String)))
        }
        let cursor = root["next_cursor"] as? String
        return (tasks, cursor?.isEmpty == false ? cursor : nil)
    }

    /// "2026-09-26" (tum gun, yerel gun basi) ya da "2026-09-26T15:00:00" / "...Z".
    public static func parseDue(_ text: String?) -> Date? {
        guard let text, !text.isEmpty else { return nil }
        if text.count == 10 {
            let f = DateFormatter()
            f.locale = Locale(identifier: "en_US_POSIX")
            f.dateFormat = "yyyy-MM-dd"
            return f.date(from: text)
        }
        let iso = ISO8601DateFormatter()
        if let d = iso.date(from: text) { return d }
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.dateFormat = "yyyy-MM-dd'T'HH:mm:ss"
        return f.date(from: text)
    }

    /// Tarihi olmayanlar en sonda.
    public static func sorted(_ tasks: [TodoTask]) -> [TodoTask] {
        tasks.sorted { ($0.due ?? .distantFuture) < ($1.due ?? .distantFuture) }
    }
}

// MARK: - Klasor yigini

public struct StackFile: Sendable, Equatable {
    public let url: URL
    public let name: String
    public let modified: Date
    public let isDirectory: Bool

    public init(url: URL, name: String, modified: Date, isDirectory: Bool) {
        self.url = url
        self.name = name
        self.modified = modified
        self.isDirectory = isDirectory
    }
}

public enum FolderStack {
    /// "date": yeniden eskiye (Windows varsayilani), "name": ada gore.
    public static func sorted(_ files: [StackFile], by sort: String, limit: Int = 30) -> [StackFile] {
        let visible = files.filter { !$0.name.hasPrefix(".") }
        let ordered = sort == "name"
            ? visible.sorted { $0.name.localizedStandardCompare($1.name) == .orderedAscending }
            : visible.sorted { $0.modified > $1.modified }
        return Array(ordered.prefix(limit))
    }
}
